### ISSUE TITLE
Sample Code

### ISSUE THREAD

**Issue by ssbanerje** [patriciogonzalezvivo/ofxGame#1]
Hi,
The video seems really great. Could you guys put up some sample code which one might look at to start using ofxGame?

Cheers,
Subho.

**Comment by headwinds** [comment]
speaking of the video - you should add a link to it in the README file ;-D

http://vimeo.com/26873181

and possibly the link to the discussion about it:

http://forum.openframeworks.cc/index.php?topic=6844.0

that's how I just found you - I googled "openframeworks 2d games" and found your project on the first page

**Comment by jorditost** [comment]
Hola Patricio,
There's already a sample code to get started using ofxGame?
Thanks!
